### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: dlopen failed: library "libmarsxlog.so" not found

### ISSUE THREAD

**Issue by hgaharwar** [wlanjie/trinity#106]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmarsxlog.so" not found
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.trinity.sample, PID: 11554
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libmarsxlog.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.trinity.sample.TrinityApplication.<clinit>(TrinityApplication.kt:24)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:47)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1052)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5877)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by hgaharwar** [comment]
version 0.3.0

**Comment by wlanjie** [comment]
only support armeabi-v7a and amr64-v8a

**Comment by hgaharwar** [comment]
my phone supports amr64-v8a

**Comment by badcodercpp** [comment]
@hgaharwar are you using library as module ? provide correct path in setting.gradle and in app/build.gradle its working on arm64-v8a, tested on xiaomi-note 4,5

**Comment by wlanjie** [comment]
Since it cannot be reproduced, it is closed
