### ISSUE TITLE
Can't able to fix the issue it was crashing while clicking

### ISSUE THREAD

**Issue by vinayak2106** [wlanjie/trinity#128]
java.lang.UnsatisfiedLinkError: No implementation found for long com.trinity.record.TrinityRecord.create() (tried Java_com_trinity_record_TrinityRecord_create and Java_com_trinity_record_TrinityRecord_create__)
        at com.trinity.record.TrinityRecord.create(Native Method)
        at com.trinity.record.TrinityRecord.startPreview(TrinityRecord.kt:189)
        at com.trinity.record.TrinityRecord.createSurface(TrinityRecord.kt:168)
        at com.trinity.camera.TrinityPreviewView.surfaceCreated(TrinityPreviewView.kt:48)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:710)
        at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:145)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2427)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1446)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6954)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:980)
        at android.view.Choreographer.doCallbacks(Choreographer.java:792)
        at android.view.Choreographer.doFrame(Choreographer.java:724)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:966)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6711)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by dhirajuchil007** [comment]
Did you manage to fix this issue? I am facing the same thing
