### ISSUE TITLE
Crash while extorting video in MI device

### ISSUE THREAD

**Issue by kishanverma26** [wlanjie/trinity#36]
`W/System.err: android.media.MediaCodec$CodecException: Error 0xfffffc0e
06-23 12:16:33.057 28057-28720/com.app W/System.err:     at android.media.MediaCodec.native_configure(Native Method)
06-23 12:16:33.057 28057-28720/com.app W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:580)
06-23 12:16:33.057 28057-28720/com.app W/System.err:     at com.trinity.encoder.MediaCodecSurfaceEncoder.start(MediaCodecSurfaceEncoder.kt:57)
06-23 12:16:33.057 28057-28720/com.app W/System.err:     at com.trinity.editor.TrinityVideoExport.createMediaCodecSurfaceEncoderFromNative(VideoExport.kt:154)`

**Comment by kishanverma26** [comment]
i am sharing crash logs with you

**Comment by wlanjie** [comment]
I need to crash the phone model, specific time, to analyze the reported information

**Comment by abkoradiya** [comment]
2020-07-26 19:52:16.704 12353-12495/com.trinity.sample I/ExtendedACodec: setupVideoEncoder()
2020-07-26 19:52:16.704 12353-12495/com.trinity.sample W/OMXUtils: do not know color format 0x7fa30c04 = 2141391876
2020-07-26 19:52:16.705 12353-12495/com.trinity.sample W/OMXUtils: do not know color format 0x7f000789 = 2130708361
2020-07-26 19:52:16.723 12353-12495/com.trinity.sample I/ACodec: setupAVCEncoderParameters with [profile: High] [level: Level32]
2020-07-26 19:52:16.728 12353-12495/com.trinity.sample I/ACodec: [OMX.qcom.video.encoder.avc] cannot encode HDR static metadata. Ignoring.
2020-07-26 19:52:16.728 12353-12495/com.trinity.sample I/ACodec: setupVideoEncoder succeeded
2020-07-26 19:52:16.729 12353-12495/com.trinity.sample I/ExtendedACodec: [OMX.qcom.video.encoder.avc] configure, AMessage : AMessage(what = 'conf', target = 1) = {
      int32_t color-format = 2130708361
      int32_t i-frame-interval = 1
      string mime = "video/avc"
      int32_t width = 720
      int32_t bitrate = 18432000
      int32_t frame-rate = 25
      int32_t height = 1280
      int32_t encoder = 1
    }
2020-07-26 19:52:16.733 12353-12495/com.trinity.sample W/OMXUtils: do not know color format 0x7f000789 = 2130708361
2020-07-26 19:52:16.747 12353-12495/com.trinity.sample W/ExtendedACodec: Failed to get extension for extradata parameter
2020-07-26 19:52:16.808 12353-12491/com.trinity.sample E/trinity: [audio_encoder_adapter.cc, Init, 47]:enter Init
2020-07-26 19:52:16.808 12353-12384/com.trinity.sample A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40e19c9 in tid 12384 (Thread-386), pid 12353 (.trinity.sample)
2020-07-26 19:52:16.809 12353-12491/com.trinity.sample E/trinity: [audio_encoder_adapter.cc, Init, 65]:leave Init

**Comment by abkoradiya** [comment]
2020-07-26 20:41:45.286 29412-29453/com.trinity.sample W/System.err: android.media.MediaCodec$CodecException: Error 0xfffffc0e
2020-07-26 20:41:45.295 29412-29453/com.trinity.sample W/System.err:     at android.media.MediaCodec.native_configure(Native Method)
2020-07-26 20:41:45.295 29412-29453/com.trinity.sample W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:1960)
2020-07-26 20:41:45.295 29412-29453/com.trinity.sample W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:1889)
2020-07-26 20:41:45.296 29412-29453/com.trinity.sample W/System.err:     at com.trinity.encoder.MediaCodecSurfaceEncoder.start(MediaCodecSurfaceEncoder.kt:57)
2020-07-26 20:41:45.296 29412-29453/com.trinity.sample W/System.err:     at com.trinity.record.TrinityRecord.createMediaCodecSurfaceEncoderFromNative(TrinityRecord.kt:780)

**Comment by abkoradiya** [comment]
https://stackoverflow.com/a/40229942/7783718

**Comment by wlanjie** [comment]
This is the encoder that created mediacodec failed, causing the coding task to crash, and there will be time to fix it later
