### ISSUE TITLE
editor crashing while scrolling back

### ISSUE THREAD

**Issue by hgaharwar** [wlanjie/trinity#39]
logs are empty but editor crashes while dragging back to start

**Comment by hgaharwar** [comment]
W/System.err: java.lang.IllegalStateException
W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
        at com.trinity.decoder.MediaCodecDecode.dequeueOutputBufferIndex(MediaCodecDecode.kt:139)
W/System.err: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2635)
        at com.trinity.decoder.MediaCodecDecode.dequeueInputBuffer(MediaCodecDecode.kt:116)
W/System.err: java.lang.IllegalStateException
W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
        at com.trinity.decoder.MediaCodecDecode.dequeueOutputBufferIndex(MediaCodecDecode.kt:139)
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2635)
        at com.trinity.decoder.MediaCodecDecode.dequeueInputBuffer(MediaCodecDecode.kt:116)

**Comment by wlanjie** [comment]
This is a bug, waiting to be fixed

**Comment by hgaharwar** [comment]
is this bug in android medaicodec class or in the library

**Comment by Vishrtr** [comment]
Any update on the mentioned bug?
