### ISSUE TITLE
Error at app opening

### ISSUE THREAD

**Issue by rocky8roy** [wlanjie/trinity#48]
java.lang.UnsatisfiedLinkError: No implementation found for void com.trinity.record.TrinityRecord.setFrame(long, int) (tried Java_com_trinity_record_TrinityRecord_setFrame and Java_com_trinity_record_TrinityRecord_setFrame__JI)
        at com.trinity.record.TrinityRecord.setFrame(Native Method)
        at com.trinity.record.TrinityRecord.setFrame(TrinityRecord.kt:238)
        at com.abc.xyz.RecordActivity.setFrame(RecordActivity.kt:182)
        at com.abc.xyz.RecordActivity.onCreate(RecordActivity.kt:144)
        at android.app.Activity.performCreate(Activity.java:7151)
        at android.app.Activity.performCreate(Activity.java:7142)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2923)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3078)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6854)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

Please check

**Comment by wlanjie** [comment]
see #22
