### ISSUE TITLE
Sample app crash on DraggingThumbLineBar

### ISSUE THREAD

**Issue by komal80501** [wlanjie/trinity#70]
Log - W/System.err: android.media.MediaCodec$CodecException: Error 0xfffffff3
        at android.media.MediaCodec.releaseOutputBuffer(Native Method)
W/System.err:     at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2834)
        at com.trinity.decoder.MediaCodecDecode.releaseOutputBuffer(MediaCodecDecode.kt:157)
W/System.err: android.media.MediaCodec$CodecException: Error 0xfffffff3
        at android.media.MediaCodec.releaseOutputBuffer(Native Method)
        at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2834)
        at com.trinity.decoder.MediaCodecDecode.releaseOutputBuffer(MediaCodecDecode.kt:157)

**Comment by shashankjha1994** [comment]
Hey, if you've been working on this for a bit and are open to helping each other fix certain aspects of the library, feel free to reach me at shashank@webloomsolutions.com.

P.S : Looking for folks to co-build/extend this library to add more features.

**Comment by wlanjie** [comment]
A version will be sent to jcenter recently

**Comment by ganeshappentus** [comment]
I am still facing the same issue..? @wlanjie have you updated the version?

**Comment by hemant279** [comment]
Guys any solution would be helpful.

**Comment by wlanjie** [comment]
no, Still under development

**Comment by rajatpathak** [comment]
I found the issues is of Null pointer in Native C++ libraries,  but it's taking more than expected time to solve the same! 
any luck from your end, my brother? @wlanjie

**Comment by Vishrtr** [comment]
Hi guys,

Did anybody come up with the bug solution?

**Comment by OneBusyBrain** [comment]
Any update on the new version when it will be released.

**Comment by OneBusyBrain** [comment]
Issues are still there in the new version updated, sound cannot be added and crashes while sliding for adding the effects

**Comment by wlanjie** [comment]
Please refer to #95 Provide crash information and log file

**Comment by phoenixvk** [comment]
@komal80501 @wlanjie I am cheking communities. Is this a memory issue? Or do we need to add RenderScripts on top of Sample app? 
Follow up will be helpful thanks :)

**Comment by badcodercpp** [comment]
have a look on https://github.com/wlanjie/trinity/issues/107#issuecomment-708061142
